EXE = generate_whitebox
EXE_WHITEBOX = whitebox
REPORT = report.pdf
ATTACK_AES = attack_aes

all: build

build: 
	@cd src && $(MAKE)
	@cp -f src/$(EXE) ./

build_whitebox:
	@cd src && $(MAKE) whitebox
	@cp -f src/$(EXE_WHITEBOX) ./

attack:
	@cd src && $(MAKE)
	@cp -f src/$(EXE) ./
	./generate_whitebox 2b7e151628aed2a6abf7158809cf4f3c
	@cd attack && make
	@cp -f attack/attack_aes ./

report:
	@cd report && $(MAKE)
	@cp -f report/$(REPORT) ./

clean:
	@cd src && $(MAKE) clean
	@cd report && $(MAKE) clean
	@cd attack && $(MAKE) clean
	@rm -f $(EXE) $(EXE_WHITEBOX) $(REPORT) $(ATTACK_AES)

help:
	@echo "Usage:"
	@echo " make [all]\t\tBuild"
	@echo " make build\t\tBuild the software"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"

.PHONY: all build build_whitebox attack report clean help
